# itsf-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: itsf-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: itsf-service
  template:
    metadata:
      labels:
        app: itsf-service
    spec:
      containers:
      - name: itsf-service
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html-content
          mountPath: /usr/share/nginx/html
        - name: nginx-config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: nginx.conf
      volumes:
      - name: html-content
        configMap:
          name: itsf-html
      - name: nginx-config
        configMap:
          name: itsf-nginx-conf
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: itsf-html
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <body>
      HELLO ITSF
    </body>
    </html>
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: itsf-nginx-conf
data:
  nginx.conf: |
    server {
        listen 80;
        server_name localhost;
        root /usr/share/nginx/html;
        location / {
            index index.html;
        }
    }
---
apiVersion: v1
kind: Service
metadata:
  name: itsf-service
spec:
  selector:
    app: itsf-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80