apiVersion: apps/v1
kind: Deployment
metadata:
  name: risf-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: risf-service
  template:
    metadata:
      labels:
        app: risf-service
    spec:
      securityContext:
        fsGroup: 101
        runAsNonRoot: true
      containers:
      - name: risf-service
        image: risf-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        securityContext:
          runAsUser: 101
          runAsGroup: 101
          allowPrivilegeEscalation: false
        volumeMounts:
        - name: temp-volume
          mountPath: /tmp
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
      volumes:
      - name: temp-volume
        emptyDir: {}
      - name: nginx-config
        configMap:
          name: nginx-conf
---
apiVersion: v1
kind: Service
metadata:
  name: risf-service
spec:
  selector:
    app: risf-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080